---
name: Build and Release Dotnet 6 Console App

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build Console App for Linux
      run: dotnet build openai-playground/openai-playground.csproj -c Release -r linux-x64

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Linux Release Asset
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: openai-playground/bin/Release/net6.0/linux-x64/openai-playground
        asset_name: openai-playground-linux-x64
        asset_content_type: application/octet-stream

    - name: Build Console App for macOS (arm64)
      run: dotnet build openai-playground/openai-playground.csproj -c Release -r osx-arm64

    - name: Upload macOS (arm64) Release Asset
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: openai-playground/bin/Release/net6.0/osx-arm64/openai-playground
        asset_name: openai-playground-macos-arm64
        asset_content_type: application/octet-stream

    - name: Build Console App for macOS (x86_64)
      run: dotnet build openai-playground/openai-playground.csproj -c Release -r osx-x64

    - name: Upload macOS (x86_64) Release Asset
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: openai-playground/bin/Release/net6.0/osx-x64/openai-playground
        asset_name: openai-playground-macos-x64
        asset_content_type: application/octet-stream
