---
name: Build and Release Dotnet 6 Console App

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build Console App
      run: dotnet build openai-playground/openai-playground.csproj -c Release -r linux-x64

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_ID: ${{ steps.create_release.outputs.release_id }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this release:
          - Build Dotnet 6 Console App
        draft: false
        prerelease: false
      # Write the environment file to disk
      run: echo "RELEASE_ID=${{ env.RELEASE_ID }}" >> $GITHUB_ENV

    - name: Upload Release Asset
      if: env.RELEASE_ID != ''
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ env.RELEASE_ID }}/assets{?name,label}
        asset_path: openai-playground/bin/Release/net6.0/linux-x64/openai-playground
        asset_name: openai-playground-linux-x64
        asset_content_type: application/octet-stream
